"use client";
import Image from "next/image";
import Link from "next/link";

export default function Footer() {
  return (
    <footer className="mt-16 border-t border-[#78c850]/20 bg-white/90">
      <div className="container mx-auto px-4 sm:px-6 py-6 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="text-sm text-gray-600">
          © {new Date().getFullYear()} NineKiwi. All rights reserved.
        </div>
        <Link href="https://ninekiwi.com" target="_blank" className="inline-flex items-center gap-2 group" aria-label="Generated by NineKiwi">
          <Image
            src="/logo.png"
            alt="NineKiwi logo"
            width={24}
            height={24}
            className="rounded-sm transition-transform duration-300 group-hover:scale-110"
            priority
          />
          <span className="text-sm font-medium text-gray-700 group-hover:text-[#78c850]">
            generated by ninekiwi.com
          </span>
        </Link>
      </div>
    </footer>
  );
}

